[tool.black]
line-length = 100
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
float_to_top = true
src_paths = ["vimception", "tests"]
skip_gitignore = true

[tool.mypy]
files = ["vimception", "tests"]
disallow_untyped_defs = true
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
